"""Generate a 2E-CTP instance file in the project format.

The script reads its parameters from a YAML config file so the values can be
edited directly without using a long command-line parser.
"""

from __future__ import annotations

import random
import re
from pathlib import Path

import yaml


DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parents[1] / "tests" / "instances"
PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CONFIG_PATH = PROJECT_ROOT / "configs" / "generate_instance.yaml"


def _sanitize_group_name(group_name: str) -> str:
    cleaned = group_name.strip()
    cleaned = re.sub(r"\s+", "_", cleaned)
    cleaned = re.sub(r"[^A-Za-z0-9_.-]", "_", cleaned)
    return cleaned or "instance"


def _unique_point(rng: random.Random, used_points: set[tuple[int, int]], coord_min: int, coord_max: int) -> tuple[int, int]:
    if coord_max < coord_min:
        raise ValueError("coord_max must be greater than or equal to coord_min")

    capacity = (coord_max - coord_min + 1) ** 2
    if len(used_points) >= capacity:
        raise ValueError("Coordinate grid is full; increase the coordinate range")

    while True:
        point = (rng.randint(coord_min, coord_max), rng.randint(coord_min, coord_max))
        if point not in used_points:
            used_points.add(point)
            return point


def _build_instance_text(
    group_name: str,
    demand_count: int,
    cover_count: int,
    hub_count: int,
    cap1: float,
    cap2: float,
    cost1: float,
    cost2: float,
    time1: float,
    time2: float,
    time3: float,
    rng: random.Random,
    coord_min: int = 0,
    coord_max: int = 100,
) -> str:
    if demand_count < 0 or cover_count < 0 or hub_count < 0:
        raise ValueError("Node counts must be non-negative")

    instance_name = f"{_sanitize_group_name(group_name)}-d{demand_count}-c{cover_count}-h{hub_count}"
    used_points: set[tuple[int, int]] = set()

    depot = (0, 0)
    used_points.add(depot)

    demands: list[tuple[int, int, int]] = []
    demand_upper = max(1, int(min(cap1, cap2, 20)))
    for demand_id in range(1, demand_count + 1):
        x, y = _unique_point(rng, used_points, coord_min, coord_max)
        demand_value = rng.randint(1, demand_upper)
        demands.append((demand_id, x, y, demand_value))

    covers: list[tuple[int, int, int]] = []
    for cover_id in range(1, cover_count + 1):
        x, y = _unique_point(rng, used_points, coord_min, coord_max)
        covers.append((cover_id, x, y))

    hubs: list[tuple[int, int, int]] = []
    for hub_id in range(1, hub_count + 1):
        x, y = _unique_point(rng, used_points, coord_min, coord_max)
        hubs.append((hub_id, x, y))

    lines: list[str] = [
        f"NAME : {instance_name}",
        "COMMENT : Generated by instance generator",
        "TYPE : 2E-CTP",
        f"DIMENSION : {demand_count}",
        "EDGE_WEIGHT_TYPE : EUC_2D",
        f"CAPACITY1 : {cap1}",
        f"CAPACITY2 : {cap2}",
        f"COST1 : {cost1}",
        f"COST2 : {cost2}",
        f"TIME1 : {time1}",
        f"TIME2 : {time2}",
        f"TIME3 : {time3}",
        f"DEPOT : {depot[0]} {depot[1]}",
        "NODE_COORD_SECTION",
    ]

    for demand_id, x, y, _ in demands:
        lines.append(f"{demand_id} {x} {y}")

    lines.append("DEMAND_SECTION")
    for demand_id, _, _, demand_value in demands:
        lines.append(f"{demand_id} {demand_value}")

    lines.append("COVERING_COORD_SECTION")
    for cover_id, x, y in covers:
        lines.append(f"{cover_id} {x} {y}")

    lines.append("HUB_COORD_SECTION")
    for hub_id, x, y in hubs:
        lines.append(f"{hub_id} {x} {y}")

    lines.append("EOF")
    return "\n".join(lines) + "\n"


def create_instance_file(
    group_name: str,
    demand_count: int,
    cover_count: int,
    hub_count: int,
    cap1: float,
    cap2: float,
    cost1: float,
    cost2: float,
    time1: float,
    time2: float,
    time3: float,
    output_dir: Path = DEFAULT_OUTPUT_DIR,
    seed: int | None = None,
    coord_min: int = 0,
    coord_max: int = 100,
) -> Path:
    rng = random.Random(seed)
    output_dir.mkdir(parents=True, exist_ok=True)

    instance_name = f"{_sanitize_group_name(group_name)}-d{demand_count}-c{cover_count}-h{hub_count}"
    output_path = output_dir / f"{instance_name}.vrp"
    if output_path.exists():
        return None

    content = _build_instance_text(
        group_name=group_name,
        demand_count=demand_count,
        cover_count=cover_count,
        hub_count=hub_count,
        cap1=cap1,
        cap2=cap2,
        cost1=cost1,
        cost2=cost2,
        time1=time1,
        time2=time2,
        time3=time3,
        rng=rng,
        coord_min=coord_min,
        coord_max=coord_max,
    )
    output_path.write_text(content, encoding="utf-8")
    return output_path


def _resolve_path(path_value: str | Path | None) -> Path:
    if path_value is None:
        return DEFAULT_OUTPUT_DIR

    path = Path(path_value)
    if path.is_absolute():
        return path

    return (PROJECT_ROOT / path).resolve()


def _load_config(config_path: Path) -> dict:
    with open(config_path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f) or {}
    if not isinstance(config, dict):
        raise ValueError(f"Config file must contain a mapping: {config_path}")
    return config


def main() -> None:
    config = _load_config(DEFAULT_CONFIG_PATH)

    output_path = create_instance_file(
        group_name=config["group_name"],
        demand_count=int(config["demand_count"]),
        cover_count=int(config["cover_count"]),
        hub_count=int(config["hub_count"]),
        cap1=float(config["cap1"]),
        cap2=float(config["cap2"]),
        cost1=float(config["cost1"]),
        cost2=float(config["cost2"]),
        time1=float(config["time1"]),
        time2=float(config["time2"]),
        time3=float(config["time3"]),
        output_dir=_resolve_path(config.get("output_dir")),
        seed=config.get("seed"),
        coord_min=int(config.get("coord_min", 0)),
        coord_max=int(config.get("coord_max", 100)),
    )
    if output_path is None:
        expected_name = f"{_sanitize_group_name(config['group_name'])}-d{int(config['demand_count'])}-c{int(config['cover_count'])}-h{int(config['hub_count'])}.vrp"
        print(f"Skipped existing instance: {_resolve_path(config.get('output_dir')) / expected_name}")
    else:
        print(f"Created instance: {output_path}")


if __name__ == "__main__":
    main()